# SPDX-License-Identifier: GPL-2.0-or-later
name: Quality assurance

on: [pull_request]

jobs:
  checkpatch:
    name: checkpatch
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 250
      - name: Run checkpatch review
        uses: https://github.com/okias/checkpatch-action@996b4834714c10588aad9ad4c77f7b9666d6f131
        env:
          CHECKPATCH_COMMAND: checkpatch.pl --no-tree --strict

#  checkpatch:
#    name: checkpatch
#    runs-on: codeberg-small
#    steps:
#      - uses: actions/checkout@v6
#        with:
#          fetch-depth: 250
#      - name: Run checkpatch review
#        env:
#          CHECKPATCH_FLAGS: -q --terse --no-summary --mailback --showfile
#        run: |
#          set -o xtrace
#          hashes=$(git log $FORGEJO_BASE_REF...HEAD --pretty="%H" --reverse | xargs)
#          for hash in $hashes; do
#            check_out=$(perl scripts/checkpatch.pl $CHECKPATCH_FLAGS -g $hash)
#            if [ -z "$check_out" ]; then
#              echo "  ✅  $hash  -  $(git show -s --format=%s $hash)"
#            else
#              echo "  ⚠️   $hash  -  $(git show -s --format=%s $hash)"
#              echo "$check_out[@]"
#            fi
#          done

#  yamllint:
#    name: yamllint
#    image: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 150
#      - name: Install yamllint
#        run: |
#          sudo apt-get -qq update > /dev/null
#          sudo apt-get -qq install python3-pip > /dev/null
#          pip install yamllint
#
#      - id: files
#        uses: jitterbit/get-changed-files@v1
#      - name: Run yamllint review
#        run: |
#          YAMLS="${{ steps.files.outputs.added_modified }}"
#          touch out.txt
#          for item in ${YAMLS}; do
#            if [[ "${item}" != **/*yaml ]]; then
#              continue
#            fi
#            yamllint -d "{rules: {line-length: {level: warning, max: 100}}}" \
#                     -f github ${item}
#            yamllint -d "{rules: {line-length: {level: warning, max: 100}}}" \
#                     -f standard ${item} >> out.txt
#          done
#          cat out.txt
#
#  dt-doc-validate:
#    name: dt-doc-validate
#    image: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 150
#      - name: Install dt-schema
#        run: |
#          sudo apt-get -qq update > /dev/null
#          sudo apt-get -qq install python3-pip > /dev/null
#          pip install git+https://github.com/devicetree-org/dt-schema.git@master
#
#      - id: files
#        uses: jitterbit/get-changed-files@v1
#      - name: Run dt-doc-validate review
#        run: |
#          YAMLS="${{ steps.files.outputs.added_modified }}"
#          for item in ${YAMLS}; do
#            if [[ "${item}" != **/*yaml ]]; then
#              continue
#            fi
#            # remove warning about URL
#            dt-doc-validate "${item}" #2>&1 | grep -v \
#              #"\$id: relative path/filename doesn't match actual path or filename\|expected:.*yaml#"
#          done
